global:

# ====================================================================================
# User-Customizable Values Section
# Below are the values we can safely modify to customize your Dataset Generation deployment 
# ====================================================================================
  # Namespace where the Helm chart will deploy the application resources.
  namespace: 

  # (str) Optional, when empty it will create a mongodb+service as part of independent process otherwise it will use the genie-mongodb Pod via LB.
  connection:

  # (str) Optional, when process run via Genie-be.
  process_id:

  # enable toleration ( on production env in order to allocate A100 GPUs).
  enable_toleration: 

  # support multiple GPUs per Pod.
  multiple_gpu_per_pod: 

  # Number of GPU per vllm Pod.
  number_of_gpu: 

  # (int) number of prompt-vllm's serving orbiters
  vllm_orbiter_replica: 

  # (int) number of reviewer-vllm's serving reviewer
  enable_reviewer: 
  vllm_reviewer_replica: 

  # (int) number of orbiter to work against prompt-vllm pool
  orbiter_replica: 

  # (int) number of reviewer to work against reviewer-vllm pool
  reviewer_replica: 
 
  # Hugging Face API token for accessing models and resources.
  # please make sure to have a pre defined secret exist in the namespace.
  hf_token: 

  # (str) Huggingface model identifier for the model to be used. 
  orbiter_model_hf_id: 
  reviewer_model_hf_id: 

  # List of args for vllm-orbiter startup,example:
  # - --max_model_len
  # - 16000
  # - --gpu_memory_utilization
  # - 0.88
  vllm_orbiter_args:

  # args for vllm-reviewer startup ( see vllm_orbiter_args example ) 
  vllm_reviewer_args:

  # List of envaironment variables for Reviewer Pods.
  reviewer_env:
    # (str) Model ID or name, ex: meta-llama/Llama-3.1-8B-Instruct
    REVIEWER_MODEL_HF_ID: 
    # (int) Maximum number of tokens that the model can generate in a single response.
    REVIEWER_MAX_GENERATION_LENGTH: 
    # (int) Maximum number of tokens the model can process in a single contex
    REVIEWER_MAX_CONTEXT_LENGTH: 
    # (int): Maximum number of prompts allowed in a single batch.
    REVIEWER_BATCH_SIZE: 
    # (float) Threshold for filtering or scoring responses ex: 75.0
    REVIEWER_SCORE_THRESHOLD: 

  # List of envaironment variables for prompt_lab Pods 
  #( env will be distributed on all modules: orbiter, launchpad and landing).
  promptlab_env:
    # (str) Model ID or name, ex: meta-llama/Llama-3.1-8B-Instruct 
    PROMPT_LAB_MODEL_HF_ID:
    # (int) Maximum number of tokens that the model can generate in a single response.
    PROMPT_LAB_MAX_GENERATION_LENGTH: 
    # (int) Maximum number of tokens the model can process in a single contex
    PROMPT_LAB_MAX_CONTEXT_LENGTH: 
    # (int): Maximum number of prompts allowed in a single batch.
    PROMPT_LAB_BATCH_SIZE: 
    # (int) Maximum number of prompts per batch.
    QUEUE_TARGET_SIZE: 
    # (str) project_config related ex: DeepCode
    TEMPLATE_AGENT:
    # (optional)
    TEMPLATE_NAME:
    # (str) project_config related ex: typescript
    TEMPLATE_TYPE: 
    # (int) Max retries, when prompt failed.
    MAX_RETRY: 
    # Huggingface repository and file to consume
    INPUT_DATASET_REPO: 
    INPUT_DATASET_FILE_NAME: 
    # Huggingface repository file drop location
    OUTPUT_DATASET_REPO:
    OUTPUT_DATASET_FILE_NAME:

    TEMPLATE_PROJECT_CONTEXT: 
    PROJECT_ID: 
    PROJECT_REPO: 

# ====================================================================================
# DO NOT MODIFY ANYTHING BELOW THIS LINE
# Changes made below this line may break the deployment or cause unexpected behavior.
# ====================================================================================

# vllm:
#   image:
#     repository: 
#     tag: 
#     pullPolicy: 
#   resources:
#     requests:
#       memory:  
#       cpu: 
#       gpu:  
#     limits:
#       memory: 
#       cpu: 
#       gpu: 
#   service:
#     type: 
#     port: 

# orbiter:
#   args:
#   image:
#     repository: 
#     tag:
#     pullPolicy: 
#   resources:
#     requests:
#       memory:  
#       cpu:    
#     limits:
#       memory:     
#       cpu: 

# control:
#   replicaCount: 
#   landing:
#     args:
#     replicaCount: 
#     celery_worker_concurrency: 
#     celery_worker_prefetch_count: 
#     image:
#       repository: 
#       tag: 
#       pullPolicy: 
#   launchpad:
#     image:
#       repository: 
#       tag:
#       pullPolicy: 

#   resources:
#     requests:
#       memory:    
#       cpu:       
#     limits:
#       memory:    
#       cpu: 

# reviewer:
#   args:
#   image:
#     repository: 
#     tag: 
#     pullPolicy: 
#   resources:
#     requests:
#       memory:    
#       cpu:        
#     limits:
#       memory:   
#       cpu:  

# misc:
#   resources:
#     requests:
#       memory:    
#       cpu:        
#     limits:
#       memory:  
#       cpu:   
#   mongodb:
#     image:
#       repository: 
#       tag: 
#       pullPolicy: 
#     service:
#       name: 
#       type: 
#       port: 
#     persistence:
#       enabled: true
#       size: 
#       storageClass: 
#   rabbitmq:
#     image:
#       repository: 
#       tag: 
#       pullPolicy: 
#     service:
#       name: 
#       type: 
#       port: 
#       managementPort: 
