apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-orbiter
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}-orbiter
spec:
  replicas: {{ .Values.global.vllm_orbiter_replica}}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}-orbiter
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}-orbiter
    spec:
      initContainers:
      - name: wait-for-services
        image: images.paas.redhat.com/genie/ubi8:latest
        env:
        - name: RELEASE_NAME
          value: {{.Release.Name | upper}}
        - name: CHART_NAME
          value: {{ .Chart.Name }}
        command: 
        - sh
        - -c
        - /mnt/config/wait-for-services.sh

        volumeMounts:
          - name: {{ .Release.Name }}-wait-for-services
            mountPath: /mnt/config


      containers:
      - name: {{ .Release.Name }}-{{ .Chart.Name }}-orbiter
        image: "{{.Values.image.repository}}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        #command: [ "/bin/bash", "-c", "--" ]
        #args: [ "while true; do sleep 3000000; done;" ]
        args: [
              "--model", "{{.Values.global.orbiter_model_hf_id}}",
              {{- range .Values.global.vllm_orbiter_args }}
              '{{ . }}',
              {{- end }}
           ]
        env:
        {{- if .Values.global.multiple_gpu_per_pod }}
        - name: CUDA_VISIBLE_DEVICES
          value: "0,1"
        - name: TRITON_CACHE_DIR
          value: "/tmp/.triton"
        {{- else }}
        - name: CUDA_VISIBLE_DEVICES
          value: "0"
        {{- end }}
        - name: VLLM_ENGINE_USE_TCP
          value: "1"
        - name: NCCL_P2P_DISABLE
          value: "1"  
        - name: TRANSFORMERS_CACHE
          value: "/tmp/.cache"
        - name: HF_HOME
          value: "/tmp/.cache"   
        - name: HF_HUB_ENABLE_HF_TRANSFER
          value: "1"   
        - name: VLLM_CONFIG_ROOT
          value: "/tmp/.cache"     
        - name: VLLM_CACHE_ROOT
          value: "/tmp/.cache"                    
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: "{{.Values.global.hf_token}}"
              key: token

        resources:
          requests:
            memory: {{.Values.resources.requests.memory}} 
            cpu: {{.Values.resources.requests.cpu}}
            nvidia.com/gpu: {{.Values.global.number_of_gpu}}
          limits:
            memory: {{.Values.resources.requests.memory}}
            cpu: {{.Values.resources.requests.cpu}}
            nvidia.com/gpu: {{.Values.global.number_of_gpu}}
          
        ports:
          - containerPort: 8000
        
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
            scheme: HTTP
          initialDelaySeconds: {{ ternary 900 120 .Values.global.enable_toleration }}
          periodSeconds: 60
          timeoutSeconds: 60
          successThreshold: 1
          failureThreshold: 60

        livenessProbe:
          httpGet:
            path: /health
            port: 8000
            scheme: HTTP
          initialDelaySeconds: {{ ternary 900 60 .Values.global.enable_toleration }}
          periodSeconds: 60
          timeoutSeconds: 60
          successThreshold: 1
          failureThreshold: 60

      {{- if .Values.global.multiple_gpu_per_pod }}
        volumeMounts:
          - name: dshm
            mountPath: /dev/shm
      {{- end }}

      volumes:
        - name: {{ .Release.Name }}-wait-for-services
          configMap:
            name: {{ .Release.Name }}-wait-for-services
            defaultMode: 0755

      {{- if .Values.global.multiple_gpu_per_pod }}
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: "16Gi"
      {{- end }}

      {{- if .Values.global.enable_toleration }}
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
        - key: tenant
          operator: Equal
          value: llmaas-a100
          effect: NoSchedule
      {{- end }}

      securityContext:
        seccompProfile:
          type: RuntimeDefault