import { 
  Database, 
  Code, 
  Search, 
  Brain, 
  Bot, 
  FileText,
  MessageSquare,
  Folder,
  Globe
} from 'lucide-react';

// Sample data for different resource types
export const sampleAgents = [
    {
      id: '1',
      name: 'Query Analyzer',
      description: 'Analyzes and extracts key entities from user questions',
      icon: <Search className="h-8 w-8 mb-2" />,
      type: 'nlp',
      model_name: 'gpt-4',
      temperature: 0.2,
      system_prompt: 'You are a query understanding specialist. Your task is to analyze user queries, identify their intent, and extract key entities. Provide a structured output of the intent and entities found.',
      color: 'bg-[#8A2BE2]',
    },
    {
      id: '2',
      name: 'Data Explorer',
      description: 'Explores and summarizes data from various sources',
      icon: <Database className="h-8 w-8 mb-2" />,
      type: 'retrieval',
      model_name: 'gpt-4',
      temperature: 0.3,
      system_prompt: 'You are a data exploration expert. Your role is to query, analyze, and synthesize information from various data sources. Provide clear summaries and extract relevant insights.',
      color: 'bg-[#03DAC6]',
    },
    {
      id: '3',
      name: 'Code Assistant',
      description: 'Writes and reviews code snippets',
      icon: <Code className="h-8 w-8 mb-2" />,
      type: 'coding',
      model_name: 'gpt-4',
      temperature: 0.1,
      system_prompt: 'You are a coding assistant specialized in writing clean, efficient code. Ensure proper error handling, use best practices, and provide explanations for complex implementations.',
      color: 'bg-[#FF5722]',
    },
    {
      id: '4',
      name: 'Planning Agent',
      description: 'Creates execution plans for complex tasks',
      icon: <Brain className="h-8 w-8 mb-2" />,
      type: 'planning',
      model_name: 'gpt-4',
      temperature: 0.4,
      system_prompt: 'You are a planning specialist. Your task is to break down complex objectives into clear, actionable steps. Create sequential plans that are easy to follow and execute.',
      color: 'bg-[#00B0FF]',
    },
    {
      id: '5',
      name: 'Conversation Bot',
      description: 'Engages in natural, helpful dialogue',
      icon: <Bot className="h-8 w-8 mb-2" />,
      type: 'conversation',
      model_name: 'gpt-4',
      temperature: 0.7,
      system_prompt: 'You are a helpful, friendly conversation assistant. Engage with users in a natural way, understand context, and provide relevant, accurate information while maintaining a personable tone.',
      color: 'bg-[#FFB300]',
    },
    {
      id: '6',
      name: 'Document Processor',
      description: 'Extracts and summarizes information from documents',
      icon: <FileText className="h-8 w-8 mb-2" />,
      type: 'document',
      model_name: 'gpt-4',
      temperature: 0.3,
      system_prompt: 'You are a document processing specialist. Your job is to extract key information from various document types, create accurate summaries, and identify important entities and relationships.',
      color: 'bg-[#00E676]',
    },
  ];
  
  export const sampleMCPs = [
    {
      id: 'mcp1',
      name: 'GitHub MCP',
      description: 'Connects to GitHub repositories for code analysis and management',
      icon: <Code className="h-8 w-8 mb-2" />,
      url: 'https://api.github.com/mcp',
      token: 'ghp_xxxxxxxxxxxxxxxxxxxx',
      timeout: 30,
      retry_count: 3,
      enabled: true,
      color: 'bg-[#24292e]',
    },
    {
      id: 'mcp2',
      name: 'Slack MCP',
      description: 'Integrates with Slack for message processing and channel management',
      icon: <MessageSquare className="h-8 w-8 mb-2" />,
      url: 'https://slack.com/api/mcp',
      token: 'xoxb-xxxxxxxxxxxxxxxxxxxx',
      timeout: 45,
      retry_count: 2,
      enabled: true,
      color: 'bg-[#4A154B]',
    },
    {
      id: 'mcp3',
      name: 'File System MCP',
      description: 'Provides access to local and remote file systems',
      icon: <Folder className="h-8 w-8 mb-2" />,
      url: 'file://localhost/mcp',
      token: '',
      timeout: 15,
      retry_count: 1,
      enabled: false,
      color: 'bg-[#FFA726]',
    },
  ];
  
  export const sampleRetrievers = [
    {
      id: 'ret1',
      name: 'Slack Retriever',
      description: 'Retrieves and processes messages from Slack channels',
      icon: <MessageSquare className="h-8 w-8 mb-2" />,
      type: 'slack',
      use_only_user_data: true,
      max_results: 50,
      similarity_threshold: 0.7,
      channels: ['general', 'development', 'ai-discussions'],
      selected_channels: ['general', 'development'],
      color: 'bg-[#4A154B]',
    },
    {
      id: 'ret2',
      name: 'Document Retriever',
      description: 'Searches through uploaded documents and files',
      icon: <FileText className="h-8 w-8 mb-2" />,
      type: 'document',
      use_only_user_data: false,
      max_results: 100,
      similarity_threshold: 0.8,
      file_types: ['pdf', 'docx', 'txt', 'md'],
      selected_file_types: ['pdf', 'docx'],
      color: 'bg-[#00E676]',
    },
    {
      id: 'ret3',
      name: 'Web Retriever',
      description: 'Retrieves information from web sources and URLs',
      icon: <Globe className="h-8 w-8 mb-2" />,
      type: 'web',
      use_only_user_data: true,
      max_results: 25,
      similarity_threshold: 0.6,
      domains: ['wikipedia.org', 'stackoverflow.com', 'github.com'],
      selected_domains: ['wikipedia.org'],
      color: 'bg-[#2196F3]',
    },
  ];