"""Shared utilities for .env generation and subprocess execution."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

ENV_HEADER = "# Generated by apply-local-dev-changes.py — do not commit\n"


def write_env(filepath: Path, entries: dict[str, str], *, force: bool = False) -> bool:
    """Write a .env file with a generated-by header.

    Returns True if the file was written, False if skipped (already exists).
    """
    if filepath.exists() and not force:
        return False
    lines = [ENV_HEADER]
    for key, value in entries.items():
        lines.append(f"{key}={value}\n")
    filepath.write_text("".join(lines))
    return True


def run_command(cmd: list[str], cwd: Path, *, log_file: Path | None = None) -> None:
    """Run a command.

    Stream stdout only to log file if povided, otherwise stream to terminal
    """
    print(f"    $ {' '.join(cmd)}")
    if log_file is None:
        subprocess.check_call(cmd, cwd=cwd)
        return

    with open(log_file, "a") as lf:
        result = subprocess.run(cmd, cwd=cwd, stdout=lf, stderr=subprocess.PIPE, text=True)
    if result.stderr:
        print(result.stderr, end="", file=sys.stderr)
    if result.returncode != 0:
        raise subprocess.CalledProcessError(result.returncode, cmd)
