kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: redis-insight-np
  app: redis-insight
spec:
  podSelector:
    matchLabels:
      app: redis-insight
  ingress:
    - {}
  egress:
    - {}
  policyTypes:
    - Ingress
    - Egress
