apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-insight-pvc
  labels:
    app: redis-insight
    paas.redhat.com/appcode: TAG-001
  annotations:
    kubernetes.io/reclaimPolicy: Delete
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: aws-ebs