apiVersion: v1
kind: Service
metadata:
  name: redis-insight-svc
  labels:
    app: redis-insight
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5540
      protocol: TCP
      name: http
  selector:
    app: redis-insight
