global:
  namespace: 
  model_hf_id:
  hf_token:

resources:
  requests:
    memory: "1Gi"     
    cpu: "1"       
  limits:
    memory: "1Gi"     
    cpu: "1"    

mongodb:
  replicaCount: 1
  image:
    repository: mongo
    tag: "latest"
    pullPolicy: Always
  service:
    name: mongodb
    type: LoadBalancer
    port: 27017
  persistence:
    enabled: true
    size: 8Gi
    storageClass: "aws-ebs"

rabbitmq:
  replicaCount: 1
  image: 
    repository: images.paas.redhat.com/genie/rabbitmq
    tag: "latest"
    pullPolicy: Always
  service:
    name: rabbitmq
    type: LoadBalancer
    port: 5672
    managementPort: 15672