version: "3.6"

#include:
  #- vllm.compose.yaml

networks:
  genie-network:
    driver: bridge
    name: genie-network

services:

  mongodb:
    image: docker.io/mongodb/mongodb-community-server:6.0-ubi8
    container_name: mongodb
    networks:
      - genie-network
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  rabbitmq:
    image: docker.io/rabbitmq
    container_name: rabbitmq
    networks:
      - genie-network
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=genie
      - RABBITMQ_DEFAULT_PASS=genie123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  ui:
    image: localhost/ui:latest
    build:
      context: ui
      dockerfile: Dockerfile
    ports:
      - "443:8080"  # 8443
    container_name: ui
    networks:
      - genie-network
    environment:
      - BE_URL=be:8080
      - LLM_BE_URL=llm-be:8080

    depends_on:
      be:
        condition: service_healthy
      llm-be:
        condition: service_healthy
  be:
    image: localhost/be:latest
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: be
#    command: ['sleep','infinity']
    environment:
       - BACKEND_ENV=PRODUCTION
       - MONGODB_HOST=mongodb
       - RABBITMQ_HOST=rabbitmq
    networks:
      - genie-network

    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_healthy

  llm-be:
    image: localhost/llm-be:latest
    build:
      context: llm-backend
      dockerfile: Dockerfile
    privileged: true
    ports:
      - "8443:8080"
    container_name: llm-be
    depends_on:
      mongodb:
        condition: service_healthy

    environment:
      - HUGGING_FACE_HUB_TOKEN=${HF_TOKEN}
      - HF_TOKEN=${HF_TOKEN}
      - BACKEND_ENV=PRODUCTION
      - MONGODB_HOST=mongodb
    #entrypoint: ["sleep", "infinity"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu] 
    networks:
      - genie-network
    volumes:
      - model-v:/data/models

volumes:
  mongo_data:
  rabbitmq_data:
  model-v:
