version: "3.6"

#include:
#  - vllm.compose.yaml

networks:
  genie-network:
    driver: bridge
    name: genie-network

services:

  rabbitmq:
    image: docker.io/rabbitmq
    container_name: rabbitmq
    networks:
      - genie-network
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=genie
      - RABBITMQ_DEFAULT_PASS=genie123
    #environment:
    #  - RABBITMQ_MNESIA_BASE=/data/db
    volumes:
      - rabbitmq_data:/data/db

  mongodb:
    image: docker.io/mongodb/mongodb-community-server:6.0-ubi8
    container_name: mongodb
    networks:
      - genie-network
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  reviewer:
    image: localhost/reviewer:latest
    container_name: reviewer
    networks:
      - genie-network
    build:
      context: reviewer
      dockerfile: Dockerfile

    command: reviewer
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HF_TOKEN}

  prompt_processor:
    image: localhost/prompt_lab:latest
    container_name: prompt_processor
    networks:
      - genie-network
    command: prompt_processor
    build:
      context: prompt_lab
      dockerfile: Dockerfile
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HF_TOKEN}

  prompt_submitter:
    image: localhost/prompt_lab:latest
    container_name: prompt_submitter
    networks:
      - genie-network
    command: prompt_submitter
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HF_TOKEN}

  prompt_dispatcher:
    image: localhost/prompt_lab:latest
    container_name: prompt_dispatcher
    networks:
      - genie-network
    command: prompt_dispatcher
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HF_TOKEN}

volumes:
  rabbitmq_data:
  mongo_data:
