version: "3.6"

networks:
  genie-network:
    driver: bridge
    name: genie-network

services:

  model-man-finetune:
    image: localhost/model-man:latest
    build:
      context: model-man
      dockerfile: Dockerfile
    container_name: model-man-finetune
    environment:
      - HUGGING_FACE_HUB_USER=zhoueric
      - HUGGING_FACE_HUB_TOKEN=${HF_TOKEN}
      - GENIE_MODEL_NAME=oodeh/openshift-qe-r64-a16-epoch20
    networks:
      - genie-network
    volumes:
      - model-v:/data/models

  model-man-general:
    image: localhost/model-man:latest
    build:
      context: model-man
      dockerfile: Dockerfile
    container_name: model-man-general
    environment:
      - HUGGING_FACE_HUB_USER=zhoueric
      - HUGGING_FACE_HUB_TOKEN=${HF_TOKEN}
      - GENIE_MODEL_NAME=unsloth/Meta-Llama-3.1-8B-Instruct-bnb-4bit
    networks:
      - genie-network
    volumes:
      - model-v:/data/models
    #command:  "echo ${HUGGING_FACE_HUB_USER}:$HUGGING_FACE_HUB_TOKEN@huggingface.co/$GENIE_MODEL_NAME && git clone https://$HUGGING_FACE_HUB_USER:$HUGGING_FACE_HUB_TOKEN@huggingface.co/$GENIE_MODEL_NAME /data/models"

  vllm-finetune:
    image: docker.io/vllm/vllm-openai:latest
    privileged: true
    ports:
      - "8001:8000"
    container_name: vllm-finetune
    depends_on:
      model-man-finetune:
        condition: service_completed_successfully
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HF_TOKEN}
    command:  '--model /data/models/openshift-qe-r64-a16-epoch20 --max-model-len  6560 --quantization bitsandbytes --load-format bitsandbytes --gpu-memory-utilization 0.9'

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu] 
    networks:
      - genie-network
    volumes:
      - model-v:/data/models

  vllm:
    image: docker.io/vllm/vllm-openai:latest
    privileged: true
    ports:
      - "8000:8000"
    container_name: vllm
    depends_on:
      model-man-general:
        condition: service_completed_successfully
    command:  '--model /data/models/Meta-Llama-3.1-8B-Instruct-bnb-4bit --max-model-len  106288 --quantization bitsandbytes --load-format bitsandbytes --gpu-memory-utilization 0.9'
    #command: "meta-llama/Llama-3.1-8B-Instruct unsloth/Meta-Llama-3.1-8B-Instruct-bnb-4bit"
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HF_TOKEN}

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu] 
    networks:
      - genie-network
    volumes:
      - model-v:/data/models

volumes:
  model-v:
