[supervisord]
nodaemon=true
logfile=/tmp/supervisord.log
logfile_maxbytes=10MB
logfile_backups=5
loglevel=info
pidfile=/tmp/supervisord.pid

[unix_http_server]
file=/tmp/supervisor.sock
chmod=0700

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[program:celery]
directory=/opt/app-root/src/backend
command=/bin/bash -c "source venv/bin/activate && celery -A celery_app.init worker --loglevel=info --concurrency=1"
priority=10
autostart=true
autorestart=true
startretries=3
stdout_logfile=/tmp/celery.log
stderr_logfile=/tmp/celery.err
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
stdout_logfile_backups=5
stderr_logfile_backups=5

[program:celery-beat]
directory=/opt/app-root/src/backend
command=/bin/bash -c "source venv/bin/activate && celery -A celery_app.init beat --loglevel=info"
priority=10
autostart=true
autorestart=true
startretries=3
stdout_logfile=/tmp/celery-beat.log
stderr_logfile=/tmp/celery-beat.err
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
stdout_logfile_backups=5
stderr_logfile_backups=5

[program:app]
directory=/opt/app-root/src/backend
command=/bin/bash -c "source venv/bin/activate && python app.py"
priority=20
autostart=true
autorestart=true
startretries=3
