{{- if .Values.volumes.modelCache.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vllm-qwen3.fullname" . }}-model-cache
  labels:
    {{- include "vllm-qwen3.labels" . | nindent 4 }}
    {{- if .Values.labels }}
    {{- toYaml .Values.labels | nindent 4 }}
    {{- end }}
  annotations:
    kubernetes.io/reclaimPolicy: "Delete"
    {{- if .Values.volumes.modelCache.retainOnDelete }}
    "helm.sh/resource-policy": keep
    {{- end }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  accessModes:
    - {{ .Values.volumes.modelCache.accessMode }}
  {{- if .Values.volumes.modelCache.storageClass }}
  storageClassName: {{ .Values.volumes.modelCache.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.volumes.modelCache.size }}
{{- end }} 