apiVersion: v1
kind: Service
metadata:
  name: {{ include "vllm-qwen3.fullname" . }}
  labels:
    {{- include "vllm-qwen3.labels" . | nindent 4 }}
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "vllm-qwen3.selectorLabels" . | nindent 4 }} 