apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  replicas: {{ .Values.global.orbiter_replica }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}
    spec:
      securityContext:
      
      initContainers:

      - name: wait-for-services
        image: images.paas.redhat.com/genie/ubi8:latest
        env:
        - name: RELEASE_NAME
          value: {{.Release.Name| upper}}
        - name: CHART_NAME
          value: {{ .Chart.Name }}
        command: 
        - sh
        - -c
        - "/mnt/config/wait-for-services.sh"

        volumeMounts:
          - name: {{ .Release.Name }}-wait-for-services
            mountPath: /mnt/config
            readOnly: true

      volumes:
      - name: {{ .Release.Name }}-wait-for-services
        configMap:
          name: {{ .Release.Name }}-wait-for-services
          defaultMode: 0755
          
      containers:        
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}

        args: [
          {{- range .Values.args }}
          '{{ . }}',
          {{- end }}
          {{- if .Values.global.enable_reviewer }}
          '--reviewer'
          {{- end }}
        ]

        #command: [ "/bin/bash", "-c", "--" ]
        #args: [ "while true; do sleep 3000000; done;" ]

        env:
        - name: HF_HOME
          value: "/tmp/.cache"  
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: "{{.Values.global.hf_token}}"
              key: token
        {{- range $key, $value := .Values.global.promptlab_env }}
        - name: "{{ $key }}"
          value: "{{ $value }}"
        {{- end }}
        

        - name: RABBITMQ_IP
          value: $({{ .Release.Name | upper }}_RABBITMQ_SVC_SERVICE_HOST)
        - name: RABBITMQ_PORT
          value: $({{ .Release.Name | upper }}_RABBITMQ_SVC_SERVICE_PORT)

        {{- if .Values.global.connection }}
        - name: MONGODB_IP
          value: {{ .Values.global.connection }}
        - name: MONGODB_PORT
          value: "27017"
        {{- else }}
        - name: MONGODB_IP
          value: $({{ .Release.Name | upper }}_MONGODB_SVC_SERVICE_HOST)
        - name: MONGODB_PORT
          value: $({{ .Release.Name | upper }}_MONGODB_SVC_SERVICE_PORT)
        {{- end }}
        
        {{- if .Values.global.process_id }}
        - name: PROCESS_ID
          value: {{ .Values.global.process_id }}
        {{- end }}

        - name: MODEL_API_URL
          value: "http://$({{ .Release.Name | upper }}_VLLM_ORBITER_SVC_SERVICE_HOST):$({{ .Release.Name | upper }}_VLLM_ORBITER_SVC_SERVICE_PORT)"


        resources:
          requests:
            memory: {{.Values.resources.requests.memory}}
            cpu: {{.Values.resources.requests.cpu}}
          limits:
            memory: {{.Values.resources.limits.memory}}
            cpu: {{.Values.resources.limits.cpu}}

      securityContext:
        seccompProfile:
          type: RuntimeDefault