apiVersion: v1
kind: Pod
metadata:
  name: multi-agent-celery
  labels:
    app: {{ .Values.global.app}}
  namespace: {{ .Values.global.namespace }}
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: multi-agent-celery
      image: 'images.paas.redhat.com/sfiresht/multia:latest'
      imagePullPolicy: Always
      stdin: true
      tty: true
      command: ["/bin/bash"]
      resources:
        limits:
          cpu: '4'
          memory: '32Gi'
        requests:
          cpu: '4'
          memory: '16Gi'
      # ports:
      #   - containerPort: 8080
      # securityContext:
      #   allowPrivilegeEscalation: false
      #   capabilities:
      #     drop:
      #       - ALL
