global:
  connection:
  process_id:
  namespace: 
  promptlab_env:

replicaCount: 1 
landing:
  args:
  - landing
  - --celery
  - --celery-worker-concurrency
  - 1
  - --celery-worker-prefetch-count
  - 1
  celery_worker_concurrency: 1
  celery_worker_prefetch_count: 1
  image:
    repository: images.paas.redhat.com/genie/prompt_lab 
    tag: "latest"
    pullPolicy: Always
launchpad:
  image:
    repository: images.paas.redhat.com/genie/prompt_lab 
    tag: "latest"
    pullPolicy: Always

resources:
  requests:
    memory: "4Gi"     
    cpu: "2"       
  limits:
    memory: "4Gi"     
    cpu: "2"   
