from flask import Blueprint
from webargs import fields
from helpers.apiargs import from_query, from_body
from be_utils.utils import json_response
from backend.providers.rag import parsed_elements_metadata_expansion, query_meta_data_retrieval, project_graph_expansion, meta_data_to_graph_retrieval,\
                                  get_context_by_packages, get_available_package_names_list_by_project, buzz_words_appearance_hash_table

rag_bp = Blueprint("rag", __name__)

@rag_bp.route("/", methods=["GET"])
def sanity_check():
    return 'There is access to API RAG Backend\n'

@rag_bp.route("/registerNewProject", methods=["GET"])
@from_body({"parsed_elements_location":      fields.Str(load_default='', data_key="parsedElementsLocation"),
             "project_name":                  fields.Str(load_default='', data_key="projectName"),
             "project_repo_path":             fields.Str(load_default='', data_key="projectRepoPath"),
             "naming_mapping":                fields.Dict(load_default={}, data_key="namingMapping"),
             "built_in_keys":                 fields.List(fields.Str(), load_default=[], data_key="builtInKeys"),
             "exclude_types":                 fields.List(fields.Str(), load_default=[], data_key="excludeTypes"),
             "project_programming_languages": fields.List(fields.Str(), load_default=[], data_key="projectProgrammingLanguages"),
})
def register_new_project(parsed_elements_location, project_name, project_repo_path, naming_mapping, built_in_keys, exclude_types, project_programming_languages):
    """map new project parsed elements with relevant metdata, add all of the expanded elements to new DB collection

    :param str parsed_elements_location: representing file location of where the dedicated project parsed elements are located (generated by the parser)
    :param str project_name:
    :param str project_repo_path: git repository link of the dedicated project
    :param dict naming_mapping: key:value naming for each parsed object metdata (which will be saved in dedicated DB collection)
    :param list built_in_keys: what are all the default keys reside under the parsed objects which we will map to the metadata
    :param list exclude_types: what are all the "elements_types" of the different parsed objects which we don't want to map
    :param list project_programming_languages: what are the programming languages being used in the git repo for the dedicated project 
    :return:
    """
    parsed_elements_metadata_expansion(parsed_elements_location, project_name, project_repo_path, naming_mapping, built_in_keys, exclude_types, project_programming_languages)
    return json_response({"result": "metadata added successfully for each of the parsed elements\n"})

@rag_bp.route("/queryRetrieval", methods=["GET"])
@from_query({"text":                          fields.Str(load_default='', data_key="text"),
            "project_name":                   fields.Str(load_default='', data_key="projectName"),
            "model_name":                     fields.Str(load_default='', data_key="modelName"),
            "model_id":                       fields.Str(load_default='', data_key="modelId"),
})
def query_retrieval(text, project_name, model_name, model_id):
    """retrieving best matched elements baed on the user query for specific project

    :param str text: user query for the LLM
    :param str project_name:
    :param str project_repo_path: git repository link of the dedicated project
    :param str model_name: current model name which being served by VLLM
    :param str model_id: current model id which being served by VLLM
    :return:
    """
    best_match = query_meta_data_retrieval(text, project_name, model_name, model_id)
    return json_response({"result": best_match})

@rag_bp.route("/buzzWordsAppearanceCounter", methods=["GET"])
@from_query({"project_name":                   fields.Str(load_default='', data_key="projectName"),
             "model_name":                     fields.Str(load_default='', data_key="modelName"),
             "model_id":                       fields.Str(load_default='', data_key="modelId"),
})
def buzz_words_appearance_counter(project_name, model_name, model_id):
    """checking for each of the buzz words in certain project - total number of appearances 

    :param str project_name:
    :param str model_name: current model name which being served by VLLM
    :param str model_id: current model id which being served by VLLM
    :return:
    """
    buzz_words_appearance = buzz_words_appearance_hash_table(project_name, model_name, model_id)
    return json_response({"result": buzz_words_appearance})

@rag_bp.route("/queryRetrievalByPackagesNames", methods=["POST"])
@from_body({"packages_list":                 fields.List(fields.Str(), load_default=[], data_key="packagesList"),
            "project_name":                  fields.Str(load_default='',   data_key="projectName"),
            "model_id":                      fields.Str(load_default='',   data_key="modelId"),
            "tokenizer_path":                fields.Str(load_default='',   data_key="tokenizerPath"),
            "context_length":                fields.Int(load_default=8192, data_key="contextLength"),
})
def context_enrichment_by_packages_selection(packages_list, project_name, model_id, tokenizer_path, context_length):
    """retrieving best matched elements based on packages list attached to user selection for specific project

    :param str packages_list: list of packages - selected by the user
    :param str project_name: project name of the model which being served by VLLM
    :param str model_id: model id which being served by VLLM
    :param str tokenizer_path: 
    :param str context_length: 
    :return:
    """
    best_match = get_context_by_packages(packages_list, project_name, model_id, tokenizer_path, context_length)
    return json_response({"result": best_match})

@rag_bp.route("/packagesNamesList", methods=["POST"])
@from_body({"project_name":                  fields.Str(load_default='', data_key="projectName"),
            "model_id":                      fields.Str(load_default='', data_key="modelId"),
})
def get_avaliable_package_names_list(project_name, model_id):
    """get the entire avaliable package list for specific project

    :param str project_name: project name of the model which being served by VLLM
    :param str model_id: model id which being served by VLLM
    :return:
    """
    best_match = get_available_package_names_list_by_project(project_name, model_id)
    return json_response({"result": best_match})

@rag_bp.route("/registerProjectGraph", methods=["GET"])
@from_body({"repo_location":      fields.Str(load_default='', data_key="repoLocation"),
            "project_name":       fields.Str(load_default='', data_key="projectName"),
            "project_repo_path":  fields.Str(load_default='', data_key="projectRepoPath"),            
            "repo_languages":     fields.List(fields.Str(), load_default=["go", "python"], data_key="repoLanguages"),
})
def register_project_graph(repo_location, project_name, project_repo_path, repo_languages):
    """map new project parsed elements with relevant metdata, add all of the expanded elements to new DB collection

    :param str repo_location: representing the path where the repo is cloned 
    :param str project_name:
    :param str project_repo_path: git repository link of the dedicated project
    :param list repo_languages: what are all the programming languages being used in the repo
    :return:
    """
    project_graph_expansion(repo_location, project_name, project_repo_path, repo_languages)
    return json_response({"result": "graph represention for each code element in the project added successfully\n"})

@rag_bp.route("/metadataRetrieval", methods=["POST"])
@from_body({"project_name":       fields.Str(load_default='', data_key="projectName"),
            "relevant_metadata":  fields.List(fields.Tuple((fields.Str(), fields.Str())), load_default=[], data_key="relevantMetadata")})
def meta_data_retrieval(project_name, relevant_metadata):
    """retrieving best matched graph elements baed on the provided metadata

    :param list relevant_metadata: tuples of relevant metadata containing element names with there relative path in the repository
    :return:
    """
    llm_context = meta_data_to_graph_retrieval(project_name, relevant_metadata)
    return json_response({"result": llm_context})