multiagent_server:
  resources: 
    limits:
      cpu: '4'
      memory: '32Gi'
    requests:
      cpu: '4'
      memory: '16Gi'
  image: 
    repository: images.paas.redhat.com/unifai/multiagent/backend
    tag: "latest"
  service:
    type: ClusterIP
    port: "8080"
  env:
    BACKEND_ENV: "production" #options - production development
    ROLE: "debug" # options are flask celery debug

multiagent_celery:
  image: 
    registry: "dummy"
    repository: "dummy"
    tag: "latest"
  service:
    type: "dummy"
    port: "dummy"