mongodb:
  image:
    registry: "images.paas.redhat.com/genie"
    repository: "mongo"
    pullPolicy: IfNotPresent
  service:
    type: LoadBalancer
    port: 27017

qdrant:
  replicaCount: 1
  image:
    registry: "images.paas.redhat.com/genie"
    repository: "qdrant"
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: LoadBalancer
    port: 6333

rabbitmq:
  image:
    registry: images.paas.redhat.com/genie
    repository: rabbitmq
    pullPolicy: IfNotPresent
    tag: 4.0.5-debian-12-r0
  service:
    type: LoadBalancer

unifai_dataflow_shared_storage:
  storage:
    volumeName: unifai-dataflow-shared-storage
    requestedSize: 50Gi
    className: aws-efs-tier-c1
    accessModes:
      - ReadWriteMany
    annotations:
      kubernetes.io/reclaimPolicy: Delete
    labels:
      paas.redhat.com/appcode: TAG-001