backend:
  image:
    repository: images.paas.redhat.com/unifai/sharedresources/ssobackend
    tag: "latest"
    pullPolicy: Always
  env:
    ROLE: "flask"
    BACKEND_ENV: "production"

  service:
    name: sso-backend
    port: 13456
  type: ClusterIP

# TODO : follow up story for sso-nginx GENIE-812
# nginx:
#   image:
#     repository: images.paas.redhat.com/unifai/sharedresources/ssonginx
#     tag: "latest"
#     pullPolicy: Always
  
#   env:
#     ROLE: "debug"
#     BACKEND_ENV: "production"

#   service:
#     name: sso-nginx
#     port: 8080
#   type: ClusterIP
