apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  labels:
    {{- include "multiagent.labels" . | nindent 4 }}
  name: {{ include "multiagent.fullname" . }}
spec:
  host: 
  port:
    targetPort: {{ .Values.service.port}}
  to:
    kind: Service
    name: {{ include "multiagent.fullname" . }}
    weight: 100
  wildcardPolicy: None
