global:
  connection:
  process_id:
  namespace: 
  orbiter_replica:
  promptlab_env: 
  enable_reviewer:

args:
- orbiter
- --celery
- --celery-worker-concurrency
- 4
- --celery-worker-prefetch-count
- 2

resources:
  requests:
    memory: "2Gi"     
    cpu: "2"       
  limits:
    memory: "4Gi"     
    cpu: "4" 

image:
  repository: images.paas.redhat.com/genie/prompt_lab
  tag: "latest"
  pullPolicy: Always