apiVersion: v1
kind: Service
metadata:
  name: {{ include "ui.fullname" . }}
  labels:
    {{- include "ui.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "ui.selectorLabels" . | nindent 4 }}
  ports:
  {{- range .Values.service.portList }}
    - name: http-{{ .name }}
      port: {{ .port }}
      targetPort: {{ .port }}
      protocol: TCP
  {{- end }}
  type: {{ .Values.service.type }} # Or NodePort if you prefer, but LoadBalancer is typical for external 