apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
  name: {{ include "mongodb.fullname" . }}
spec:
  host: 
  port:
    targetPort: 27017
  to:
    kind: Service
    name: {{ include "mongodb.fullname" . }}
    weight: 100
  wildcardPolicy: None

