ConfigMap: 
  data: 
    MODE: "training" #debug | training
    PROJECT: test_mpc_training
    DATASET_REPO: oodeh/mpc_training
    DATASET_NAME: mpc_training
ConfigMapTrainerArgs:
    metadata:
        name: trainer-configmap-trainer-args
        namespace: tag-ai--pipeline
    data: 
        MODEL_NAME_OR_PATH: "Qwen/Qwen2.5-Coder-14B-Instruct"
        LORA_RANK: "16"
        LORA_ALPHA: "16"
        LORA_DROPOUT: "0.1"
        DATASET: "mpc_training"
        TEMPLATE: "qwen"
        MAX_SAMPLES: "500000"
        NUM_TRAIN_EPOCHS: "1"
        GRADIENT_ACCUMULATION_STEPS: "16"
        PER_DEVICE_TRAIN_BATCH_SIZE: "1"
        LEARNING_RATE: "0.00005"
        QUANTIZATION: "true"
