{{- if not .Values.global.connection }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-mongodb-pvc
  namespace: {{ .Values.global.namespace }}
  annotations:
    kubernetes.io/reclaimPolicy: Delete
  labels:
    paas.redhat.com/appcode: TAG-001
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongodb.persistence.size }}
  storageClassName: {{ .Values.mongodb.persistence.storageClass }}
{{- end }}