"""Application service: .env file generation."""

from __future__ import annotations

import re
import secrets
from enum import Enum
from pathlib import Path

from devtool.domain.models import Service
from devtool.domain.registry import Registry


class GenerateResult(Enum):
    """Outcome of a single ``generate()`` call."""
    CREATED = "created"
    UPDATED = "updated"
    SKIPPED = "skipped"


_ENV_HEADER = "# Generated by unifai-dev — do not commit\n"
_PLACEHOLDER_RE = re.compile(r"<REPLACE", re.IGNORECASE)
_AUTOGEN_RE = re.compile(r"<AUTO_GENERATE", re.IGNORECASE)

_SECRET_KEY_FILE = "local-development/.dev-secret-key"
_KEYCLOAK_KEYS = {"keycloak_base_url", "client_id", "client_secret", "keycloak_realm"}


def is_auto_generate(value: str) -> bool:
    """True when *value* is an ``<AUTO_GENERATE>`` marker."""
    return bool(_AUTOGEN_RE.search(value))


def _expected_keys(service: Service, *, local_auth: bool = False) -> set[str]:
    """Return the set of env keys that should be present on disk."""
    is_identity_local = local_auth and service.name == "identity"
    keys = {
        k for k in service.env_entries
        if not (is_identity_local and k in _KEYCLOAK_KEYS)
    }
    if is_identity_local:
        keys.add("local_auth_enabled")
    return keys


def check_missing_keys(
    service: Service, root: Path, *, local_auth: bool = False,
) -> set[str]:
    """Return env-entry keys expected but absent from the on-disk file."""
    if not service.env_file or not service.env_entries:
        return set()

    env_path = root / service.directory / service.env_file
    if not env_path.exists():
        return set()

    expected = _expected_keys(service, local_auth=local_auth)

    on_disk: set[str] = set()
    with open(env_path) as f:
        for line in f:
            stripped = line.lstrip()
            if not stripped or stripped[0] == "#":
                continue
            eq = stripped.find("=")
            if eq == -1:
                continue
            on_disk.add(stripped[:eq].rstrip())

    return expected - on_disk


def align_local_auth(service: Service, root: Path, *, local_auth: bool) -> bool:
    """Ensure identity's ``local_auth_enabled`` line matches the flag.

    When *local_auth* is true, appends ``local_auth_enabled=true`` if absent.
    When false, removes any ``local_auth_enabled`` line.

    Returns True if the file was modified.
    """
    if service.name != "identity" or not service.env_file:
        return False

    env_path = root / service.directory / service.env_file
    if not env_path.exists():
        return False

    lines = env_path.read_text().splitlines(keepends=True)
    has_key = any(
        line.lstrip().startswith("local_auth_enabled=")
        for line in lines
        if not line.lstrip().startswith("#")
    )

    if local_auth and not has_key:
        with open(env_path, "a") as f:
            f.write("local_auth_enabled=true\n")
        return True

    if not local_auth and has_key:
        with open(env_path, "w") as f:
            for line in lines:
                if not line.lstrip().startswith("local_auth_enabled="):
                    f.write(line)
        return True

    return False


def get_or_create_shared_secret(root: Path) -> str:
    """Return the shared dev secret, creating it on first call.

    The key is persisted to ``local-development/.dev-secret-key``
    and is the same across all services.
    """
    secret_path = root / _SECRET_KEY_FILE
    if secret_path.exists():
        value = secret_path.read_text().strip()
        if value:
            return value
    key = secrets.token_hex(32)
    secret_path.parent.mkdir(parents=True, exist_ok=True)
    secret_path.write_text(key + "\n")
    return key


def generate(
    service: Service, root: Path, *, force: bool = False, local_auth: bool = False,
) -> GenerateResult:
    """Write or update the .env file for *service*.

    When *local_auth* is true and the service is ``identity``, Keycloak
    placeholder keys are omitted and ``local_auth_enabled=true`` is written
    instead.

    Returns ``CREATED`` for a new file, ``UPDATED`` if missing keys were
    appended to an existing file, or ``SKIPPED`` if nothing changed.
    """
    if not service.env_entries or not service.env_file:
        return GenerateResult.SKIPPED

    env_path = root / service.directory / service.env_file

    if env_path.exists() and not force:
        missing = check_missing_keys(service, root, local_auth=local_auth)
        if not missing:
            return GenerateResult.SKIPPED
        new_lines: list[str] = []
        for key in missing:
            if key == "local_auth_enabled":
                new_lines.append("local_auth_enabled=true\n")
            else:
                new_lines.append(f"{key}={service.env_entries[key]}\n")
        with open(env_path, "a") as f:
            f.writelines(new_lines)
        return GenerateResult.UPDATED

    is_identity_local = local_auth and service.name == "identity"

    lines = [_ENV_HEADER]
    for key, value in service.env_entries.items():
        if is_identity_local and key in _KEYCLOAK_KEYS:
            continue
        lines.append(f"{key}={value}\n")

    if is_identity_local:
        lines.append("local_auth_enabled=true\n")

    env_path.write_text("".join(lines))
    return GenerateResult.CREATED


def check_unresolved(
    service: Service, root: Path,
) -> tuple[set[str], set[str]]:
    """Return ``(placeholders, auto_generate)`` — keys still unresolved on disk.

    Scans the service's ``.env`` file in a single pass, checking each key
    against both the ``<REPLACE...>`` and ``<AUTO_GENERATE>`` patterns.
    """
    empty: tuple[set[str], set[str]] = (set(), set())
    if not service.env_file or not service.env_entries:
        return empty

    placeholder_suspects = {
        key for key, value in service.env_entries.items()
        if _PLACEHOLDER_RE.search(value)
    }
    autogen_suspects = {
        key for key, value in service.env_entries.items()
        if _AUTOGEN_RE.search(value)
    }
    all_suspects = placeholder_suspects | autogen_suspects
    if not all_suspects:
        return empty

    env_path = root / service.directory / service.env_file
    if not env_path.exists():
        return empty

    placeholders: set[str] = set()
    auto_gen: set[str] = set()

    with open(env_path) as f:
        for line in f:
            if not all_suspects:
                break
            stripped = line.lstrip()
            if not stripped or stripped[0] == "#":
                continue
            eq = stripped.find("=")
            if eq == -1:
                continue
            key = stripped[:eq].rstrip()
            if key not in all_suspects:
                continue
            value_start = stripped[eq + 1:eq + 20]
            if key in placeholder_suspects and _PLACEHOLDER_RE.search(value_start):
                placeholders.add(key)
            if key in autogen_suspects and _AUTOGEN_RE.search(value_start):
                auto_gen.add(key)
            all_suspects.discard(key)

    return placeholders, auto_gen


def check_placeholders(service: Service, root: Path) -> set[str]:
    """Return env-entry keys whose ``<REPLACE...>`` marker is still on disk."""
    placeholders, _ = check_unresolved(service, root)
    return placeholders


def check_auto_generate(service: Service, root: Path) -> set[str]:
    """Return env-entry keys whose ``<AUTO_GENERATE>`` marker is still on disk."""
    _, auto_gen = check_unresolved(service, root)
    return auto_gen


def collect_auto_generate_keys(registry: Registry, root: Path) -> dict[str, list[str]]:
    """Return ``{key: [service_names...]}`` for all unresolved auto-generate entries.

    Groups by key name so a single prompt can resolve all services at once.
    """
    grouped: dict[str, list[str]] = {}
    for svc in registry.all_services():
        _, auto_gen = check_unresolved(svc, root)
        for key in auto_gen:
            grouped.setdefault(key, []).append(svc.name)
    return grouped


def resolve_auto_generate_key(
    key: str, value: str, services: list[Service], root: Path,
) -> int:
    """Write *value* for *key* into every service's on-disk .env file.

    Returns the number of files updated.
    """
    updated = 0
    for svc in services:
        if not svc.env_file:
            continue
        env_path = root / svc.directory / svc.env_file
        if not env_path.exists():
            continue
        replace_env_value(env_path, key, value)
        updated += 1
    return updated


def replace_env_value(env_path: Path, key: str, new_value: str) -> None:
    """Rewrite a single ``key=...`` line in an env file."""
    lines = env_path.read_text().splitlines(keepends=True)
    with open(env_path, "w") as f:
        for line in lines:
            stripped = line.lstrip()
            if stripped.startswith(f"{key}="):
                f.write(f"{key}={new_value}\n")
            else:
                f.write(line)


def generate_all(
    registry: Registry, root: Path, *, force: bool = False,
) -> tuple[list[str], list[str], list[str], list[str]]:
    """Generate .env files for every service that needs one.

    Returns ``(generated, skipped, updated, warnings)`` — lists of relative
    file paths for generated/skipped/updated, and human-readable placeholder
    warnings.
    """
    generated: list[str] = []
    skipped: list[str] = []
    updated: list[str] = []
    warnings: list[str] = []

    for svc in registry.all_services():
        if not svc.env_entries or not svc.env_file:
            continue
        rel = str(svc.directory / svc.env_file)
        result = generate(svc, root, force=force, local_auth=registry.local_auth)
        if result is GenerateResult.CREATED:
            print(f"  ✔ Generated {rel}")
            generated.append(rel)
        elif result is GenerateResult.UPDATED:
            print(f"  ✔ Updated {rel} (added missing keys)")
            updated.append(rel)
        else:
            print(f"  ⏭ Skipped {rel} (already exists)")
            skipped.append(rel)

        if align_local_auth(svc, root, local_auth=registry.local_auth):
            if rel not in updated:
                print(f"  ✔ Updated {rel} (aligned local_auth_enabled)")
                updated.append(rel)

        placeholders, _ = check_unresolved(svc, root)
        for key in placeholders:
            warnings.append(f"  ⚠ {svc.name}: {rel}  {key} is still a placeholder!")

    return generated, skipped, updated, warnings


def show(service: Service, root: Path) -> None:
    """Print the current .env config for *service*."""
    if not service.env_file:
        print(f"{service.name}: no env file configured.")
        return

    env_path = root / service.directory / service.env_file
    if env_path.exists():
        print(f"── {env_path} ──")
        print(env_path.read_text(), end="")
    else:
        print(f"{env_path} does not exist yet.")
        if service.env_entries:
            print("Template values:")
            for k, v in service.env_entries.items():
                print(f"  {k}={v}")
