"""Application service: .env file generation."""

from __future__ import annotations

import re
from pathlib import Path

from devtool.domain.models import Service
from devtool.domain.registry import Registry

_ENV_HEADER = "# Generated by unifai-dev — do not commit\n"
_PLACEHOLDER_RE = re.compile(r"<REPLACE", re.IGNORECASE)


def generate(service: Service, root: Path, *, force: bool = False) -> bool:
    """Write the .env file for *service*.

    Returns True if the file was written, False if skipped.
    """
    if not service.env_entries or not service.env_file:
        return False

    env_path = root / service.directory / service.env_file
    if env_path.exists() and not force:
        return False

    lines = [_ENV_HEADER]
    for key, value in service.env_entries.items():
        lines.append(f"{key}={value}\n")
    env_path.write_text("".join(lines))
    return True


def check_placeholders(service: Service, root: Path) -> set[str]:
    """Return the set of env-entry keys that still hold a placeholder on disk.

    Only keys whose *template* value (in ``env_entries``) matches
    ``<REPLACE...`` are checked.  The on-disk file is streamed line-by-line;
    for each suspect key only the first few characters after ``=`` are
    inspected.  Returns an empty set when the file doesn't exist or all
    placeholders have been replaced.
    """
    if not service.env_file or not service.env_entries:
        return set()

    suspect_keys = {
        key for key, value in service.env_entries.items()
        if _PLACEHOLDER_RE.search(value)
    }
    if not suspect_keys:
        return set()

    env_path = root / service.directory / service.env_file
    if not env_path.exists():
        return set()

    found: set[str] = set()
    with open(env_path) as f:
        for line in f:
            if not suspect_keys:
                break
            stripped = line.lstrip()
            if not stripped or stripped[0] == "#":
                continue
            eq = stripped.find("=")
            if eq == -1:
                continue
            key = stripped[:eq].rstrip()
            if key not in suspect_keys:
                continue
            value_start = stripped[eq + 1:eq + 20]
            if _PLACEHOLDER_RE.search(value_start):
                found.add(key)
            suspect_keys.discard(key)

    return found


def generate_all(
    registry: Registry, root: Path, *, force: bool = False,
) -> tuple[list[str], list[str], list[str]]:
    """Generate .env files for every service that needs one.

    Returns ``(generated, skipped, warnings)`` — lists of relative file
    paths for generated/skipped, and human-readable placeholder warnings.
    """
    generated: list[str] = []
    skipped: list[str] = []
    warnings: list[str] = []

    for svc in registry.all_services():
        if not svc.env_entries or not svc.env_file:
            continue
        rel = str(svc.directory / svc.env_file)
        if generate(svc, root, force=force):
            print(f"  ✔ Generated {rel}")
            generated.append(rel)
        else:
            print(f"  ⏭ Skipped {rel} (already exists)")
            skipped.append(rel)

        placeholders = check_placeholders(svc, root)
        for key in placeholders:
            warnings.append(f"  ⚠ {svc.name}: {rel}  {key} is still a placeholder!")

    return generated, skipped, warnings


def show(service: Service, root: Path) -> None:
    """Print the current .env config for *service*."""
    if not service.env_file:
        print(f"{service.name}: no env file configured.")
        return

    env_path = root / service.directory / service.env_file
    if env_path.exists():
        print(f"── {env_path} ──")
        print(env_path.read_text(), end="")
    else:
        print(f"{env_path} does not exist yet.")
        if service.env_entries:
            print("Template values:")
            for k, v in service.env_entries.items():
                print(f"  {k}={v}")
