#this file is not needed anymore as we use jinja template to insert the values to the command below is the yaml for the config map and the values section as was

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.ConfigMapTrainCmd.metadata.name }}
  namespace: {{ .Values.ConfigMapTrainCmd.metadata.namespace }}
data: 
{{- range $key, $value := .Values.ConfigMapTrainCmd.data }}
  {{ $key }}: |
{{ $value | indent 4 }}
{{- end }}
immutable: false



ConfigMapTrainCmd:
  metadata:
    name: trainer-configmap-cmd
    namespace: tag-ai--pipeline  #tag-ai--runtime-int 
  data: 
    trainer_args.yaml: |
      ### model
      model_name_or_path: meta-llama/Llama-3.2-1B-Instruct
      #model_name_or_path: Qwen/Qwen2.5-Coder-7B-Instruct
      trust_remote_code: true 
    
      ### method
      stage: sft
      do_train: true
      finetuning_type: lora
      lora_rank: 16 
      lora_alpha: 16 
      lora_dropout: 0.1 
      lora_target: all

      ### dataset
      dataset: eco-gotest-training
      dataset_dir: data
      template: llama3  #qwen
      cutoff_len: CUTOFF_LEN   #8192 default get this from the previous script
      max_samples: 10000
      preprocessing_num_workers: 16

      ### output
      output_dir: saves/test
      logging_steps: 5
      save_steps: 253
      plot_loss: true
      overwrite_output_dir: true
      report_to: none
      packing: false

      ### train
      per_device_train_batch_size: 1
      gradient_accumulation_steps: 16
      max_grad_norm: 1.0
      flash_attn: fa2
      learning_rate: !!float 5e-05
      num_train_epochs: 20.0
      lr_scheduler_type: cosine
      warmup_ratio: 0.1
      warmup_steps: 0
      bf16: true
      ddp_timeout: 180000000
      optim: adamw_torch 
      quantization_bit: 4
      double_quantization: true
      quantization_method: bitsandbytes

