apiVersion: v1
kind: Pod
metadata:
  name: tmux
  labels:
    app: TAG-001
  namespace: tag-ai--pipeline
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: httpd
      #image: images.paas.redhat.com/genie/training:test
      image: 'image-registry.openshift-image-registry.svc:5000/openshift/httpd:latest'
      imagePullPolicy: Always
      stdin: true
      tty: true
      volumeMounts:
        - name: ssh-key-volume
          #mountPath: "/app/.ssh"
          mountPath: "/etc/ssh/keys"
          readOnly: true

  volumes:
    - name: ssh-key-volume
      secret:
        secretName: ssh-key-secret