apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "unifai-tests.fullname" . }}
  labels:
    {{- include "unifai-tests.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "unifai-tests.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "unifai-tests.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: test-runner
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - {{ .Values.testSuite | quote }}
            {{- if .Values.extraArgs }}
            {{- range (splitList " " .Values.extraArgs) }}
            - {{ . | quote }}
            {{- end }}
            {{- end }}
          {{- if .Values.reports.enabled }}
          ports:
            - name: http
              containerPort: {{ .Values.reports.service.port }}
              protocol: TCP
          {{- end }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
            - name: REPORTS_DIR
              value: "/reports"
            - name: SERVE_REPORTS
              value: {{ .Values.reports.enabled | ternary "true" "false" | quote }}
            - name: SERVE_PORT
              value: {{ .Values.reports.service.port | quote }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.reports.enabled }}
          volumeMounts:
            - name: reports
              mountPath: /reports
          {{- end }}
      {{- if .Values.reports.enabled }}
      volumes:
        - name: reports
          persistentVolumeClaim:
            claimName: {{ include "unifai-tests.reportsPvcName" . }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
