{{- if .Values.reports.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "unifai-tests.reportsPvcName" . }}
  labels:
    {{- include "unifai-tests.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.reports.storage.accessModes | nindent 4 }}
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.reports.storage.size }}
  {{- if .Values.reports.storage.className }}
  storageClassName: {{ .Values.reports.storage.className }}
  {{- end }}
{{- end }}
