{{- if and .Values.reports.enabled .Values.reports.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  labels:
    {{- include "unifai-tests.reportLabels" . | nindent 4 }}
  name: {{ include "unifai-tests.fullname" . }}-reports
spec:
  {{- if .Values.reports.route.host }}
  host: {{ .Values.reports.route.host }}
  {{- end }}
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None
  to:
    kind: Service
    name: {{ include "unifai-tests.fullname" . }}-reports
    weight: 100
  wildcardPolicy: None
{{- end }}
