"""Shared constants, types, and helpers for the env package."""

from __future__ import annotations

import re
from enum import Enum


class GenerateResult(Enum):
    """Outcome of a single ``generate()`` call."""
    CREATED = "created"
    UPDATED = "updated"
    SKIPPED = "skipped"


ENV_HEADER = "# Generated by unifai-dev — do not commit\n"
PLACEHOLDER_RE = re.compile(r"<REPLACE", re.IGNORECASE)
AUTOGEN_RE = re.compile(r"<AUTO_GENERATE", re.IGNORECASE)

SECRET_KEY_FILE = "local-development/.dev-secret-key"
LOCAL_AUTH_SERVICE = "identity"
KEYCLOAK_KEYS = {"keycloak_base_url", "client_id", "client_secret", "keycloak_realm"}


def is_auto_generate(value: str) -> bool:
    """True when *value* is an ``<AUTO_GENERATE>`` marker."""
    return bool(AUTOGEN_RE.search(value))


def expected_keys(service, *, local_auth: bool = False) -> set[str]:
    """Return the set of env keys that should be present on disk."""
    is_identity_local = local_auth and service.name == LOCAL_AUTH_SERVICE
    keys = {
        k for k in service.env_entries
        if not (is_identity_local and k in KEYCLOAK_KEYS)
    }
    if is_identity_local:
        keys.add("local_auth_enabled")
    return keys
