global:

  namespace: 
  enable_toleration: 
  multiple_gpu_per_pod:
  number_of_gpu: 
  enable_reviewer:
  vllm_orbiter_replica: 
  vllm_reviewer_replica:

  orbiter_model_hf_id:
  reviewer_model_hf_id:

  vllm_orbiter_args:
  vllm_reviewer_args:

image:
  repository: images.paas.redhat.com/genie/vllm-openai
  tag: "latest"
  pullPolicy: Always  

resources:
  requests:
    memory:  "28Gi"   
    cpu: "4"
    gpu:     
  limits:
    memory: "28Gi"   
    cpu: "8"
    gpu:   

service:
  type: ClusterIP
  port: 8000
