kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "temporal.fullname" . }}-np
  labels: 
    app: {{ .Chart.Name }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Chart.Name }}
  ingress:
    - {}
  egress:
    - {}
  policyTypes:
    - Ingress
    - Egress
