kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: temporal-np
  app: temporal
spec:
  podSelector:
    matchLabels:
      app: temporal
  ingress:
    - {}
  egress:
    - {}
  policyTypes:
    - Ingress
    - Egress
