apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: temporal-pvc
  labels:
    app: temporal
    paas.redhat.com/appcode: TAG-001
  annotations:
    kubernetes.io/reclaimPolicy: Delete
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: aws-ebs