kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: temporal-route
  app: temporal
  labels:
    paas.redhat.com/appcode: TAG-001
spec:
  host: 
  to:
    kind: Service
    name: temporal-svc
    weight: 100
  port:
    targetPort: temporal-ui
  wildcardPolicy: None