apiVersion: v1
kind: Service
metadata:
  name: temporal-svc
  labels:
    app: temporal
spec:
  type: ClusterIP
  ports:
    - port: 7233
      name: temporal
    - port: 8233
      name: temporal-ui
  clusterIP: None
  selector:
    app: temporal

