{{- if .Values.qdrant.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qdrant
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "unifai-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qdrant
  template:
    metadata:
      labels:
        app: qdrant
    spec:
      containers:
      - name: qdrant
        image: qdrant/qdrant:v1.7.4
        ports:
        - containerPort: 6333
        - containerPort: 6334
        volumeMounts:
        - name: qdrant-storage
          mountPath: /qdrant/storage
      volumes:
      - name: qdrant-storage
        persistentVolumeClaim:
          claimName: qdrant-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-pvc
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "unifai-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3-csi
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: qdrant
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "unifai-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  selector:
    app: qdrant
  ports:
  - name: http
    port: 6333
    targetPort: 6333
  - name: grpc  
    port: 6334
    targetPort: 6334
  type: ClusterIP
{{- end }}
