apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.ConfigMap.metadata.name }}
  namespace: {{ .Values.ConfigMap.metadata.namespace }}
data: 
{{- range $key, $value:= .Values.ConfigMap.data }}
   {{ $key }}: {{ $value | quote }}
{{- end }}
immutable: false