apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.PersistentVolumeClaim.metadata.name }}
  namespace: {{ .Values.Global.namespace }}
  labels:
    paas.redhat.com/appcode: {{ .Values.Global.app_code }}
  annotations:
    kubernetes.io/reclaimPolicy: {{ index .Values.PersistentVolumeClaim.metadata.annotations "kubernetes.io/reclaimPolicy" }}
spec:
  accessModes:
  {{- range .Values.PersistentVolumeClaim.spec.accessModes }}
    - {{ . }}
  {{- end }}
  volumeMode: {{ .Values.PersistentVolumeClaim.spec.volumeMode }}
  storageClassName: {{ .Values.PersistentVolumeClaim.spec.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.PersistentVolumeClaim.spec.resources.requests.storage }}