apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  labels:
    app: {{ .Values.Deployment.spec.template.metadata.labels.app }}
  name: genie-training-api
spec:
  host: 
  port:
    targetPort: http
  to:
    kind: Service
    name: genie-training-api
    weight: 100
  wildcardPolicy: None

