apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: genie-training-route
  namespace: {{ .Values.Global.namespace }}
  annotations:
    openshift.io/host.generated: "true"
  labels:
    app: {{ .Values.Global.app }}
spec:
  host: 
  port:
    targetPort: http
  to:
    kind: Service
    name: genie-training-svc
    weight: 100
  wildcardPolicy: None

