kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.Secret.metadata.name }}
  namespace: {{ .Values.Secret.metadata.namespace }}
data:
  token: {{ .Values.Secret.data.token | b64enc}}
type: Opaque