apiVersion: v1
kind: Service
metadata:
  name: genie-training-api
  labels:
    app: {{ .Values.Deployment.spec.template.metadata.labels.app }}
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.Deployment.spec.template.metadata.labels.app }}
