replicaCount: 1
image:
   repository: images.paas.redhat.com/genie/reviewer
   tag: 2025.01.02
   pullPolicy: Always
hf_token: hf_xxxxx
command: reviewer
HF_TOKEN: "hf_xxxxx"
HF_HOME: "/tmp"

RABBITMQ_IP: "rabbitmq"
RABBITMQ_PORT: 5672

MONGODB_IP: "mongodb"
MONGODB_PORT: 27017

REVIEWER_MODEL_HF_ID: "meta-llama/Llama-3.1-8B-Instruct"
REVIEWER_MAX_GENERATION_LENGTH: "4096"
REVIEWER_MAX_CONTEXT_LENGTH: "16384"
REVIEWER_BATCH_SIZE: "4"
REVIEWER_SCORE_THRESHOLD: "85.0"
