replicaCount: 1
image:
   repository: images.paas.redhat.com/genie/prompt_lab
   tag: 2025.01.13
   pullPolicy: Always
hf_token: hf_xxxxx
command: prompt_processor
HF_HOME: "/tmp/"
HF_TOKEN: "hf_xxxxx"

RABBITMQ_IP: "rabbitmq"
RABBITMQ_PORT: 5672 

MONGODB_IP: "mongodb"
MONGODB_PORT: 27017 

INPUT_JSON_PATH: ""
OUTPUT_DATA_DIR_PATH: ""

PROMPT_LAB_MODEL_HF_ID: ""
PROMPT_LAB_MAX_GENERATION_LENGTH: ""
PROMPT_LAB_MAX_CONTEXT_LENGTH: ""
PROMPT_LAB_BATCH_SIZE: ""

QUEUE_TARGET_SIZE: ""

TEMPLATE_NAME: ""
TEMPLATE_AGENT: ""
TEMPLATE_TYPE: ""

