version: "3.6"

networks:
  llm:
    driver: bridge
    name: llm

services:

  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: llm-mongodb
    networks:
      - llm
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  llm:
    image: localhost/llm-be:latest
    privileged: true
    ports:
      - "443:443"
    container_name: llm-backend
    environment:
      - HUGGING_FACE_HUB_TOKEN=hf_xxxx
    #entrypoint: ["bash", "-lc", "sleep infinity"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu] 
    networks:
      - llm

volumes:
  mongo_data:
