apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  labels:
    {{- include "sso.labels" . | nindent 4 }}
  name: {{ include "sso.fullname" . }}-backend
spec:
  host: 
  port:
    targetPort: {{ .Values.backend.service.port }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None

  to:
    kind: Service
    name: {{ .Values.backend.service.name }}
    weight: 100
  wildcardPolicy: None
