apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 6379
      name: redis
  clusterIP: None
  selector:
    app: redis

