apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "redis.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  serviceName: {{ include "redis.fullname" . }}-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      volumes:
        - name: redis-volume
          persistentVolumeClaim:
            claimName: {{ include "redis.fullname" . }}-pvc
      containers:
        - name: redis
          image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
          #args: ["--requirepass", "admin", "--appendonly", "yes", "--save", "900", "1", "--save", "30", "2"]
          ports:
            - containerPort: {{ .Values.service.port }}
              name: {{ .Values.service.name }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
            {{- end }}
          volumeMounts:
            - name: redis-volume
              mountPath: /data