apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-wait-for-services
  namespace: {{ .Values.global.namespace }}
data:
  wait-for-services.sh: |
    export REVIEWER_NUM="{{.Values.global.vllm_reviewer_replica}}"
    MONGODB_IP="{{ default (printf "%s-mongodb-svc" .Release.Name) .Values.global.connection }}:27017"
    echo "$MONGODB_IP"
    
    while [ "$(curl -s -o /dev/null -w "%{http_code}" -u genie:genie123 http://{{ .Release.Name }}-rabbitmq-svc:15672/api/overview)" != "200" ]; do
      echo "Waiting for RabbitMQ service to be ready...";
      sleep 5;
    done;
    echo "RabbitMQ service is up!"
    
    while [ "$(curl -s -o /dev/null -w "%{http_code}" http://$MONGODB_IP)" != "200" ]; do
      echo "Waiting for MongoDB service to be ready at $MONGODB_IP...";
      sleep 5;
    done;
    echo "MongoDB service is up at $MONGODB_IP."

    if [ "$CHART_NAME" != "vllm" ]; then

        while [ "$(curl -s -o /dev/null -w "%{http_code}"  http://{{ .Release.Name }}-vllm-orbiter-svc:8000/health)" != "200" ]; do
          echo "Waiting for Vllm-orbiter service to be ready...";
          sleep 20;
        done;
        echo "Vllm-orbiter service is up!"

        if [ "$REVIEWER" == "true" ]; then

          while [ "$(curl -s -o /dev/null -w "%{http_code}" http://{{ .Release.Name }}-vllm-reviewer-svc:8000/health)" != "200" ]; do
            echo "Waiting for Vllm-reviewer service to be ready...";
            sleep 20;
          done;
          echo "Vllm-reviewer service is up!"
          
        fi
    fi
