debug: false
env:
  HF_TOKEN: "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" # taguser hf_token
  VLLM_CONFIG_ROOT: '/tmp/usage'
  HF_HOME: '/tmp/'
  BACKEND_ENV: "production"
      
replicaCount: 1
image:
   repository: images.paas.redhat.com/genie/llm-backend 
   tag: latest #2025.01.13
   pullPolicy: Always
resources:
  limits:
    cpu: 4
    # -- CPU memory configuration
    memory: 16Gi
    # -- Number of gpus used
    nvidia.com/gpu: 1
service:
  type: ClusterIP
  port: 8080

