helmDefaults:
  createNamespace: false
  wait: false

releases:

  - name: unifai-dataflow-shared-storage
    chart: ./dataflow/unifai-dataflow-shared-storage
    version: "0.9.0"
    wait: true
    values:
      - ./values/dataflow-resource-values.yaml
      - valuesKey: unifai-dataflow-shared-storage


  - name: unifai-dataflow-server
    chart: ./dataflow/unifai-dataflow-server
    wait: true
    values:
      - ./values/global-config.yaml
      - ./values/dataflow-resource-values.yaml
      - valuesKey: unifai-dataflow-server

  - name: unifai-dataflow-celery
    chart: ./dataflow/unifai-dataflow-celery
    version: "0.9.0"
    wait: true
    values:
      - ./values/global-config.yaml
      - ./values/dataflow-resource-values.yaml
      - valuesKey: unifai-dataflow-celery

