# Default values for mongodb.

nameOverride: ""
fullnameOverride: "mongodb"
## Additional labels for Deployment or StatefulSet
customLabels: {}
## Additional annotations for Deployment or StatefulSet
customAnnotations: {}
securityContext: {}
image:
  registry: "images.paas.redhat.com/genie"
  repository: "mongo"
resources:
  requests:
    memory: "1Gi"     
    cpu: "1"       
  limits:
    memory: "1Gi"     
    cpu: "1"  
storage:
  ## Internal volume name and prefix of a created PVC
  volumeName: "genie-mongodb-volume"
  ## Alternative set requestedSize to define a size for a dynamically created PVC
  requestedSize: 30G
  ## Default access mode (ReadWriteOnce)
  className: aws-ebs
  accessModes:
    - ReadWriteOnce
  ## Additional storage annotations
  annotations: 
    kubernetes.io/reclaimPolicy: Delete
  labels:
    paas.redhat.com/appcode: TAG-001

networkPolicy:
  ## Ingress and Egress policies
   ingress: 
   - ports:
      - port: 27017
        protocol: TCP
   egress: {}
      


