apiVersion: v1
kind: ConfigMap
metadata:
  name: celery-configmap
  namespace: {{ .Values.global.namespace }}
data:
  role: {{ .Values.global.role }}
  mode: {{ .Values.global.mode }} 
{{- range $key, $value:= .Values.env }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
immutable: false