name: Backup Umami Database

env:

  username: "tag-ai"
  POSTGRES_POD: "umami-db-0"
  UMAMI_BACKUP_DIR: "/tmp/umami_backup"
  BRANCH: #${{ inputs.target_branch || 'GENIE-1308_umami_backup' }}
#   CLUSTER: ${{ inputs.target_cluster || 'PRE-PRODUCTION' }}
  BACKUP_REPO: ${{ vars.BACKUP_REPO_URL }}
  BACKUP_REPO_NAME: ${{ vars.BACKUP_REPO_NAME }}
  ENVIRONMENT: "UMAMI"
on:
 push:
    branches:
      - GENIE-1308_umami_backup
 workflow_dispatch:

jobs:
    backup_umami:
        runs-on: linux
        environment:
            name: ${{ vars.ENVIRONMENT }}
        env:
            API_URL: ${{ vars.API_URL }}
            ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
            SKIP_VERIFY_TLS: ${{ vars.SKIP_VERIFY_TLS }}
            NAMESPACE: ${{ vars.NAMESPACE }}
            PGHOST: ${{ vars.PGHOST }}
            PGPORT: ${{ vars.PGPORT }}
            PGUSER: ${{ vars.PGUSER }}
            PGPASSWORD: ${{ secrets.PGPASSWORD }}
            PGDATABASE: ${{ vars.PGDATABASE }}

        steps:

        - name: Checkout Code
          uses: actions/checkout@v4
          with:
              fetch-depth: 0
              ref: ${{ env.BRANCH }}

        - name: Backup Umami Database
          env:
            API_URL: ${{ vars.API_URL }}
            ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
            SKIP_VERIFY_TLS: ${{ vars.SKIP_VERIFY_TLS }}
            NAMESPACE: ${{ vars.NAMESPACE }}
            PGHOST: ${{ vars.PGHOST }}
            PGPORT: ${{ vars.PGPORT }}
            PGUSER: ${{ vars.PGUSER }}
            PGPASSWORD: ${{ secrets.PGPASSWORD }}
            PGDATABASE: ${{ vars.PGDATABASE }}
          run: python3 .github/scripts/backup_postgres.py

    upload_to_gitlab:        
        runs-on: linux
        needs: [backup_umami]
        steps:

        - name: Checkout Code
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
            ref: ${{ env.BRANCH }}

        # - name: Upload files to gitlab repo
        #     run: python3 .github/scripts/upload_to_gitlab.py
        
        # - name: Clean up
        #     run: |
        #     rm -rf /tmp/mongo_backup_*.tar.gz
        #     rm -rf /tmp/snapshots

    analyze:
        needs: [backup_umami]
        if: always() && contains(needs.*.result, 'failure')
        runs-on: ubuntu-latest
        permissions:
          actions: read
          contents: read
        steps:

        - name: Generate Token
          id: generate_token
          #uses: tibdex/github-app-token@v2
          uses: actions/create-github-app-token@v2
          with:
            app-id: ${{ secrets.LOG_ANALYZER_APP_ID }}
            private-key: ${{ secrets.LOG_ANALYZER_PRIVATE_KEY }}

        - name: GitHub Actions Failure Analysis
          uses: calebevans/gha-failure-analysis@v0.1.9
          with:
            llm-provider: gemini
            llm-model: gemini-3-pro-preview
            llm-api-key: ${{ secrets.GEMINI_API_KEY }}
            github-token: ${{ steps.generate_token.outputs.token }}
            post-pr-comment: false