name: Build UnifAIImages

on:
  push:
    branches:
      - 'GENIE-1138/build_images'
  workflow_dispatch:
    inputs:
      build_sso_image:
        description: "Build SSO backend image"
        required: false
        default: false
      build_gui:
        description: "Build UI image"
        required: false
        default: false
      build_dataflow_backend:
        description: "Build Dataflow backend image"
        required: false
        default: false
      build_multiagent_backend:
        description: "Build Multi-Agent System backend image"
        required: false
        default: false
      set_image_candidate:
    #     description: "Set image candidate"
    #     required: false
    #     default: false
    #   deploy_unifai:
    #     description: "Deploy UnifAI"
    #     required: false
    #     default: false
    #   deploy_type:
    #     description: "Deploy type"
    #     required: false
    #     default: false
    #   deploy_location:
    #     description: "Deploy location"
    #     required: false
    #     default: false
    #   debug_mode:
    #     description: "Debug mode"
    #     required: false
    #     default: false
    #   branch:
    #     description: "Branch"
    #     required: false
    #     default: "main"
    #   version:
    #     description: "Version"
    #     required: false
    #     default: "latest"
    #   df_version:
    #     description: "Dataflow version"
    #     required: false
    #     default: "latest"
    #   ma_version:
    #     description: "Multi-Agent System version"
    #     required: false
    #     default: "latest"
    #   gui_version:
    #     description: "UI version"
    #     required: false
    #     default: "latest"
    #   sso_version:
    #     description: "SSO backend version"
    #     required: false
    #     default: "latest"
    #   modules_to_deploy:
    #     description: "Modules to deploy"
    #     required: false
    #     default: "dataflow,multiagent,ui,sso"
    #   pipeline_branch:
    #     description: "Pipeline branch"
    #     required: false
    #     default: "main"


jobs:
  build_images:
    runs-on: linux
    strategy:
      # Use a matrix to define your different image locations
      matrix:
        include:
          - image_name: sso-backend
            context: shared-resources/sso-backend
            dockerfile: shared-resources/sso-backend/Dockerfile
          - image_name: ui
            context: ui
            dockerfile: ui/deployment/Dockerfile
        #   - image_name: dataflow-backend
        #     context: ./backend
        #     dockerfile: ./backend/Dockerfile
        #   - image_name: multiagent-backend
        #     context: ./multi-agent
        #     dockerfile: ./multi-agent/Dockerfile
    env:
      VERSION: 'test' #${{ github.sha }}
    steps:

      - name: check deps
        run: |
          echo "Checking dependencies"
          command -v buildah
          if [ $? -ne 0 ]; then
            echo "Installing buildah"
            sudo dnf install -y buildah
          fi
          command -v buildah
          if [ $? -ne 0 ]; then
            echo "Installing buildah"
            sudo dnf install -y buildah
          fi


      - name: Checkout Code
        uses: actions/checkout@v4

        - name: Checkout GitLab repository (genie-cred-data)
        run: |
          git clone git@gitlab.cee.redhat.com:ai_tools/genie-cred-data.git genie-cred-data
      
      - name: Log in to image paas registry
        run: |
          mkdir -p $HOME/.config/containers
          echo "${{ secrets.IMAGE_REGISTRY_PASSWORD }}" | podman login ${{ vars.IMAGE_REGISTRY_URL }} \
          --username "${{ vars.IMAGE_REGISTRY_USERNAME }}" \
          --password-stdin
          echo "REGISTRY_AUTH_FILE=$HOME/.config/containers/auth.json" >> $GITHUB_ENV

        # Use Buildah to build the image
      - name: Build ${{ matrix.image_name }} Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ matrix.image_name }}
          tags: ${{ vars.IMAGE_REGISTRY_URL }}/unifai/temp/${{ matrix.image_name }}:${{ env.VERSION }}
          containerfiles: |
            ${{ matrix.dockerfile }}
          context: . ####${{ matrix.context }}

      # Add this step to push the image
      - name: Push ${{ matrix.image_name }} Image to Registry
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ matrix.image_name }}
          tags: ${{ vars.IMAGE_REGISTRY_URL }}/unifai/temp/${{ matrix.image_name }}:${{ env.VERSION }}
          registry: ${{ vars.IMAGE_REGISTRY_URL }}
          username: ${{ vars.IMAGE_REGISTRY_USERNAME }}
          password: ${{ secrets.IMAGE_REGISTRY_PASSWORD }}